export const Questions = [
  {
    prompt:
      "Which framework is built on top of Node.js and is used for building web applications?",
    optionA: "Angular",
    optionB: "Express.js",
    optionC: "React",
    optionD: "Vue.js",
    answer: "B",
  },
  {
    prompt: "Which of the following is NOT a valid HTML element?",
    optionA: "<article>",
    optionB: "<container>",
    optionC: "<header>",
    optionD: "<nav>",
    answer: "B",
  },
  {
    prompt: "What does CSS stand for?",
    optionA: "Creative Style Sheets",
    optionB: "Cascading Style Sheets",
    optionC: "Computer Style Sheets",
    optionD: "Colorful Style Sheets",
    answer: "B",
  },
  {
    prompt: "In React, what is used for handling stateful logic?",
    optionA: "Functional components",
    optionB: "Class components",
    optionC: "Hooks",
    optionD: "Higher-order components",
    answer: "C",
  },
  {
    prompt: "What type of NoSQL database is MongoDB?",
    optionA: "Document database",
    optionB: "Key-value database",
    optionC: "Column-family database",
    optionD: "Graph database",
    answer: "A",
  },
  {
    prompt: "What is Node.js used for?",
    optionA: "Front-end web development",
    optionB: "Server-side web development",
    optionC: "Database management",
    optionD: "Mobile app development",
    answer: "B",
  },
  {
    prompt: "What does SASS stand for?",
    optionA: "Syntactically Awesome Style Sheets",
    optionB: "Style and Structure Sheets",
    optionC: "Simple Application Style Sheets",
    optionD: "Stylish and Smart Sheets",
    answer: "A",
  },
  {
    prompt: "What is the purpose of the HTML 'meta' tag?",
    optionA: "Define a section of navigation links",
    optionB: "Declare character encoding of the document",
    optionC: "Create a pop-up window",
    optionD: "Style the document content",
    answer: "B",
  },
  {
    prompt: "What is the purpose of the 'useEffect' hook in React?",
    optionA: "Managing state in functional components",
    optionB: "Handling side effects in functional components",
    optionC: "Creating reusable components",
    optionD: "Styling components with CSS",
    answer: "B",
  },
  {
    prompt: "What is the purpose of the 'async' keyword in JavaScript?",
    optionA: "Declare a function that returns a Promise",
    optionB: "Define a function that can be awaited",
    optionC: "Indicate a function is executed asynchronously",
    optionD: "All of the above",
    answer: "D",
  },
];
